### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by malcommac** [sachinkesiraju/SKPanoramaView#3] opened 2015-02-27 23:09 UTC
Tried to run the example project (iOS 8.1)
This is the result:

'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 368]'

**Comment by sachinkesiraju** [comment] 2015-03-02 18:46
Hmm, that's odd. Unfortunately, I wasn't able to reproduce the bug. Were you by any chance using an iPad to test this?

**Comment by MacKentoch** [comment] 2015-03-27 13:33
It works (iOS 8.2).
But it has same problems as my own implementation : on simulator press "COMMAND" + "SHIFT" + "H" (go back home) then enter back app; animation is freezed...
If you find a good solution feel free to tell. 

Btw already good job and thx sharing!

**Comment by bigship** [comment] 2015-04-22 00:53
@MacKentoch  I think I found a way to restart the animation, you can try to do this below:

``` objective-c
// in your view controller's viewDidLoad method, register a notification handler
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(restartAnimation:)
name:UIApplicationDidBecomeActiveNotification object:nil];

// reset the image again, and the animation will restart
- (void)restartAnimation {
    [self.your_panoramaView setImage:yourImage];
    [self.your_panoramaView startAnimating];
} 
```

It works for me, but the solution is not perfect. It can only **RESTART** the animation from scratch, not **RESUME** the animation in the middle. You got better idea?

**Comment by MacKentoch** [comment] 2015-04-22 03:28
Hi,

I ended by using a timer to execute ya animation second by second.

I had observers to watch UIApplicationDidBecomeActiveNotification, and UIApplicationDidEnterBackgroundNotification, thanks to that I can resume or restart my animation.

It works, when I go home, my application stops my animated background.
And don’t bug when I come back in my application.

I gonna soon push an example on github.

**Comment by bigship** [comment] 2015-04-22 08:12
@MacKentoch can't wait to see your example

**Comment by MacKentoch** [comment] 2015-04-22 12:20
Just a matter of time (busy days^^), but be sure I work on it.

In my read, I gonna add a link to your repos as a special thanks since you inspired it.

First time will begin swift without easy install implementation.
Juste a demo to share with the community the way I used.


I’ll tell you when it’s done.

**Comment by MacKentoch** [comment] 2015-04-22 17:55
Ok it is ready here : https://github.com/MacKentoch/EDAAnimatedBackgroundImage <https://github.com/MacKentoch/EDAAnimatedBackgroundImage>

Next time I’ll make it more reusable, it is just a demo right now.

**Comment by MacKentoch** [comment] 2015-04-22 20:44
In fact I don’t resume position when coming back.

I didn’t notice you already had a solution like me.

To resume position : 
- I need to check which constraint and how much time for animation after resume.
- Then need to check wether going right to left or left to right.

I’ll get it just a matter of time like every time^^

**Comment by MacKentoch** [comment] 2015-04-23 11:20
# 1st STEP DONE 

Ok it is ready here : [EDAAnimatedBackgroundImage](https://github.com/MacKentoch/EDAAnimatedBackgroundImage)
- Next time I’ll make it more reusable, it is just a demo right now.
- Right now I don’t resume position when coming back; it starts from beginning.

_I didn’t notice you already had a solution like me._

# NEXT STEP (WORKING ON IT) - _experimental_2 branch_

To resume position : 
- I can't use same Animation since it is reversed and infinite (repeat)
  - otherwise as an example, if I restart same animation that ended at 50%, animation will stand next doing only 50% infinite loop : 

My code here to illustrate  :

```
UIView.animateWithDuration(duration
           , delay: 0.0
           , options: UIViewAnimationOptions.Repeat | UIViewAnimationOptions.Autoreverse
           , animations:
           {

             self.view.layoutIfNeeded()
             //layoutIfNeeded is not animated, the trick to animate is to set alpha to 1.0 as it is already
             self.view.alpha = 1.0
        },
        completion: { finished in
            self.secondElapse = self.secondElapse! + 1
            self.lastPosToReach = self.backImageTrailingConstraint.constant
            println("      ... 1 sec elapsed" +
                    "\ncurrent constraint constant : \(self.lastPosToReach)" +
                    "\ncurrent time elapsed since animation started in this direction : \(self.secondElapse)" +
                    "\n")

        }
    )
```
- At resume, 
  - I need to check wether going right to left or left to right (depends on self.secondElapse being or not > duration (=40 in my case)
  - I need to layout my background Image as it was before going Home (constraint.constant value won't tell you, I need to estimate with self.secondElapse).
  - finish animation (with another no infinite animation) till the point animation should reverse by itself
  - then restart the main animation (infinite and autoreverse).

# CONCLUSION  

That is how I see it but will need some efforts, so a bit time^^.
And if all I said was wrong, i need to find another way. But I feel I'm on a good way.

**Comment by MacKentoch** [comment] 2015-04-24 03:51
# New version v0.2 (master branch)

[here it is - master branch](https://github.com/MacKentoch/EDAAnimatedBackgroundImage)
I merged my experimental branch since I found it cool alternative to resume animation from background.
- now resuming application
  - launch a short animation to reset background image in its initial state from last position (before going background)
  - then, main animation restart (infinite, autoreverse).
- If you have a look on it, watch your target output in Xcode 
  - to see verbose mode of the animation
  - seeing that constraint (used to animate) value don't change even animation occurs
    - so it is not reliable to check a position at an instant T
  - see that my counter (counting seconds elapsed) makes the deal to evaluate 
    - direction change
    - and background image position (since constraint does not give a clue)

---

**Now I'm still working on a resume that looks like animation don't care application goes background.**

**Closed as completed** 2015-10-07 21:45 UTC
